name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_SANITY_URL: ${{ secrets.NEXT_PUBLIC_SANITY_URL }}
          NEXT_PUBLIC_SANITY_TOKEN: ${{ secrets.NEXT_PUBLIC_SANITY_TOKEN }}
          NEXT_PUBLIC_SANITY_LATEST_PROJECTS: ${{ secrets.NEXT_PUBLIC_SANITY_LATEST_PROJECTS }}
          NEXT_PUBLIC_SANITY_ALL_PROJECTS: ${{ secrets.NEXT_PUBLIC_SANITY_ALL_PROJECTS }}
          NEXT_PUBLIC_SANITY_PROJECTS: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECTS }}
          NEXT_PUBLIC_SANITY_PROJECT_BY_CATEGORY: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_BY_CATEGORY }}

      - name: Export
        run: npm run export

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: out
